/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package site.zpweb.barker.model.db;

import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.annotations.Indexes;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;

/**
 * Definition of ObjectType Follow.
 *
 * @since 2021-08-05
 */
@PrimaryKeys({"id"})
@Indexes({"follow_id:id"})
public final class Follow extends BaseCloudDBZoneObject {
    private Integer follower_user_id;

    private Integer following_user_id;

    public Follow() {
        super(Follow.class);
    }

    public void setFollower_user_id(Integer follower_user_id) {
        this.follower_user_id = follower_user_id;
    }

    public Integer getFollower_user_id() {
        return follower_user_id;
    }

    public void setFollowing_user_id(Integer following_user_id) {
        this.following_user_id = following_user_id;
    }

    public Integer getFollowing_user_id() {
        return following_user_id;
    }

}
