/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package site.zpweb.barker.model.db;

import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;

/**
 * Definition of ObjectType Like.
 *
 * @since 2021-08-05
 */
@PrimaryKeys({"id"})
public final class Like extends BaseCloudDBZoneObject {

    private Integer post_id;

    private Integer user_id;

    public Like() {
        super(Like.class);
    }

    public void setPost_id(Integer post_id) {
        this.post_id = post_id;
    }

    public Integer getPost_id() {
        return post_id;
    }

    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    public Integer getUser_id() {
        return user_id;
    }

}
